# Generated by Django 4.1 on 2022-08-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('mail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('token', models.CharField(default=None, max_length=200)),
            ],
        ),
    ]
